debug: true

db:
  driver: mysql       # mysql, postgres
  user:   admin
  pass:   admin
  host:   localhost
  port:   3306        # 3306, 5432
  name:   db

instagram:
  timeout_min: 1000   # ms
  timeout_max: 3000   # ms
  users:
  - name:     login
    password: password
  - name:     login
    password: password